dist: trusty
language: java
jdk:
  - openjdk8
sudo: false
script: ./mvnw clean verify cobertura:cobertura-integration-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/cobertura/coverage.xml -DprojectToken=${CODACY_TOKEN} -DapiToken=${CODACY_TOKEN}